#!/usr/bin/env bash

# This is partially based on the No Boilerplate script.

rebuild() {
    set -e
    pushd ~/Projects/dotfiles/nixos/src
    
    git diff -U0 "*.nix"
    git add .
    echo "Rebuilding NixOs."
    sudo nixos-rebuild switch -I nixos-config=src/configuration.nix \
        --flake .\#$HOSTNAME \
        &>../nixos-switch.log || (cat ../nixos-switch.log | grep --color error && exit 1)
    
    current=$(nixos-rebuild list-generations | grep current)
    
    git commit -am "$current"
    
    # diffs=$(git diff --name-only src/)
    # echo $diffs
    
    # for f in $diffs; do echo "${f}"; done
    
    popd
    
    notify-send -e "NixOS rebuilt." --icon=software-update-available
}


upgrade() {
    set -e
    pushd ~/Projects/dotfiles/nixos/src
    
    git diff -U0 "*.nix"
    git add .
    echo "Rebuilding and upgrading NixOs."
    sudo nixos-rebuild switch --upgrade -I nixos-config=src/configuration.nix \
        --flake .\#$HOSTNAME \
        &>../nixos-switch.log || (cat ../nixos-switch.log | grep --color error && exit 1)
    
    current=$(nixos-rebuild list-generations | grep current)
    
    git commit -am "$current"
    
    # diffs=$(git diff --name-only src/)
    # echo $diffs
    
    # for f in $diffs; do echo "${f}"; done
    
    popd
    
    notify-send -e "NixOS rebuilt." --icon=software-update-available
}

collect_garbage() {
    sudo nix-collect-garbage -d --delete-older-than 7d
    sudo nix-collect-garbage
}

optimize () {
    sudo nix-store --optimise
}

usage() {
    echo "using rebuild-system"
    echo "-h    show this help"
    echo "-*    rebuild the system without updating packages"
    echo "-d    remove all unnecessary packages and system versions older than one week"
    echo "-o    optimize storage space using nix-store --optimise"
    # echo ""
    echo "-u    rebuild and upgrade the operating system."
}

no_args="true"

while getopts "oudh" option; do
    case "$option" in 
        u) # upgrade packages
            upgrade
            # echo "no";
            exit 0
            ;;
        h) # show help
            usage
            ;;
        d) # collect garbage
            collect_garbage
            # echo "yes";
            exit 0
            ;;
        o)
            optimize
            ;;
        *) # rebuild system
            # rebuild
            # echo "maybe";
            exit 0
            ;;
    esac
    no_args="false"
done

# This just rebuilds the system if no options are present. I blame bash's syntax
# for this.
[[ "$no_args" == "true" ]] && { rebuild; exit 0; }
